# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/FPGA/fpga-pl_uart/pl_uart/pl_uart.srcs/sources_1/bd/zynq_uart_fifo_axi/ip/zynq_uart_fifo_axi_processing_system7_0_0/zynq_uart_fifo_axi_processing_system7_0_0.xci
# IP: The module: 'zynq_uart_fifo_axi_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/fpga-pl_uart/pl_uart/pl_uart.gen/sources_1/bd/zynq_uart_fifo_axi/ip/zynq_uart_fifo_axi_processing_system7_0_0/zynq_uart_fifo_axi_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_uart_fifo_axi_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/FPGA/fpga-pl_uart/pl_uart/pl_uart.srcs/sources_1/bd/zynq_uart_fifo_axi/ip/zynq_uart_fifo_axi_processing_system7_0_0/zynq_uart_fifo_axi_processing_system7_0_0.xci
# IP: The module: 'zynq_uart_fifo_axi_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/fpga-pl_uart/pl_uart/pl_uart.gen/sources_1/bd/zynq_uart_fifo_axi/ip/zynq_uart_fifo_axi_processing_system7_0_0/zynq_uart_fifo_axi_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_uart_fifo_axi_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
