domain_path: D:\FPGA\fpga-pl_uart\pl_uart\pl_uart.sdk\myPlatform\export\myPlatform\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
