set_property SRC_FILE_INFO {cfile:D:/FPGA/fpga-pl_uart/pl_uart/pl_uart.srcs/constrs_1/new/my_xdc.xdc rfile:../../../pl_uart.srcs/constrs_1/new/my_xdc.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L14 [get_ports i_RX_0]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L15 [get_ports o_TX_0]
