# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/my_xdc.xdc

# Block Designs: bd/zynq_uart_fifo_axi/zynq_uart_fifo_axi.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_uart_fifo_axi || ORIG_REF_NAME==zynq_uart_fifo_axi} -quiet] -quiet

# IP: bd/zynq_uart_fifo_axi/ip/zynq_uart_fifo_axi_processing_system7_0_0/zynq_uart_fifo_axi_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_uart_fifo_axi_processing_system7_0_0 || ORIG_REF_NAME==zynq_uart_fifo_axi_processing_system7_0_0} -quiet] -quiet

# IP: bd/zynq_uart_fifo_axi/ip/zynq_uart_fifo_axi_ps7_0_axi_periph_0/zynq_uart_fifo_axi_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_uart_fifo_axi_ps7_0_axi_periph_0 || ORIG_REF_NAME==zynq_uart_fifo_axi_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/zynq_uart_fifo_axi/ip/zynq_uart_fifo_axi_rst_ps7_0_50M_0/zynq_uart_fifo_axi_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_uart_fifo_axi_rst_ps7_0_50M_0 || ORIG_REF_NAME==zynq_uart_fifo_axi_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/zynq_uart_fifo_axi/ip/zynq_uart_fifo_axi_auto_pc_0/zynq_uart_fifo_axi_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_uart_fifo_axi_auto_pc_0 || ORIG_REF_NAME==zynq_uart_fifo_axi_auto_pc_0} -quiet] -quiet

# XDC: d:/FPGA/fpga-pl_uart/pl_uart/pl_uart.gen/sources_1/bd/zynq_uart_fifo_axi/zynq_uart_fifo_axi_ooc.xdc
